# Generated by Django 5.0.4 on 2024-12-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canid', models.IntegerField()),
                ('cname', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=1000)),
                ('feedbackdt', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
